### ISSUE TITLE
remove/migrate Jekyll styler metadata from page headers

### ISSUE THREAD

**Issue by noatamir** [numfocus/DISCOVER-Cookbook#50]
Most of the pages have Jekyll style metadata like this at the top of each page:

```markdown
---
layout: page
title: Childcare
---

# Childcare

**Tags:** <span style="color:red">Parents and Carers</span>, <span style="color:red">Participant Diversity</span>, <span style="color:red">Scholarships</span>

✅ Offer financial support for childcare.
 - Build it into your budget. 
   - Link it to sponsorships, or university partners, ...
```

Jbook uses different metadata, need to research more, but it's built on top of Sphinx, so is similar. May not need them at all because jbook automatically creates table of contents and sections from markdown headers like `# Childcare` automatically.

**Comment by mikofski** [comment]
copied from temporary transition repo "discover-handbook"
https://github.com/numfocus/DISCOVER-handbook/issues/6

**Comment by mikofski** [comment]
according to jupyter book documentation, references to sections and docs can be adding a label role like this:

```
(About=)
# About
```

then reference the "About" section anywhere in the cookbook as either <code>{ref}`About\`</code> or as `[](About)`. In fact since this is a document it could also be referenced using the `{doc}` directive or markdown as `[](./About.md)`, see: [Reference Content Files](https://jupyterbook.org/en/stable/content/references.html#reference-content-files).

* https://jupyterbook.org/en/stable/content/references.html
* https://jupyterbook.org/en/stable/tutorials/references.html
